### ISSUE TITLE
Stables menu stops working

### ISSUE THREAD

**Issue by Crowlikedream** [VORPCORE/VORP-Stables#19]
If a player chooses Horse Dealer > Choose a Horse > Choose Horse Color > Buy for xxx$ > then get the naming window, but changes their mind and closes the naming window by clicking the X in the corner, they cannot get past the Buy for xxxS to get to name the horse and actually purchase the horse until they relog.

The same thing happens if a player actually purchases a horse. If they later return to the stables to purchase another horse, they cannot get past the Buy for xxx$ and get to name and purchase another horse until they relog.

This does not happen on either way when dealing with carts.

**Comment by Local9** [comment]
Require more information, please re-open with a video and showing the process if this is still an issue.
