### ISSUE TITLE
Config.json is same as Config_es.json

### ISSUE THREAD

**Issue by Athran-z** [VORPCORE/VORP-Stables#25]
Looks like the config.json was overridden and is also in spanish. currently there is no English language for menu text.

**Comment by EdWordy** [comment]
the english for the original file is buried in the commit history. Hopefully this helps.

https://github.com/VORPCORE/VORP-Stables/commit/11a6c81306b278e2e586c45eb711d706a2c998fe

**Comment by MartensMalsero** [comment]
Is this still relevant? If so, please let me know exactly what is wrong. I have not yet been able to find the error in the files.
