### ISSUE TITLE
Horse accessories bug

### ISSUE THREAD

**Issue by twigmasters** [VORPCORE/VORP-Stables#5]
I set up vorp core 2.0 and updated all the resources. I was able to buy a horse but when I tried to add saddles etc. It doesn't take my money and then I try to call my horse and it wont spawn. So I relog and call my horse and its there so repeat the process trying to buy a saddle and same problem.

Any ideas?

**Comment by rubi216** [comment]
Does the script throw any errors?

**Comment by twigmasters** [comment]
I didn't see any errors in the client console or server. A friend helping me test bought a horse and ran into the same problem.

**Comment by twigmasters** [comment]
Just out of curiosity I tried replacing the edited version ( just edited prices) with a fresh downloaded version and same problem. I currently have a horse with a saddle and everything but I did have an issue when I got it initially, I don't remember how I got around it. Now when I try to change something on my horse it wont take my money and after I try, I can't call my horse until I relog.

**Comment by rubi216** [comment]
And do you have scripts that arent official VORP scripts? Because if it doesnt show any error its probably because a non official script that isnt using the new API

**Comment by twigmasters** [comment]
I did a bunch of testing and by disabling on script at a time I found it was the old version of the RPchat script. I have replaced it with the new version and its all working now. Don't ask me what RPchat has to do with the stables but who knows why one broke the other.

Thanks for the help

**Comment by rubi216** [comment]
You are welcome!
