### ISSUE TITLE
[Request] Place pricing on the interface

### ISSUE THREAD

**Issue by Dontrell94** [VORPCORE/VORP-Stables#7]
Apparently the pricing isn't shown on the stables, so you get to the end after customizing and told how much you pay. It would be very helpful, if it was possible, to see how much the pricing is before purchase much similar to the way online and SP handle it.

**Comment by ghost** [comment]
I'll take a whack at this one soon™.

**Comment by MartensMalsero** [comment]
@Dontrell94 @bythewood fixed witth #16 & #18

**Comment by hulguu** [comment]
Horse stash will be
Appears when saving item

live console print, debug spaming 

https://media.discordapp.net/attachments/1013487110407331950/1032019708939075584/unknown.png

**Comment by MartensMalsero** [comment]
@hulguu Please open new Issues for your concerns in the future.

**Comment by hulguu** [comment]
@MartensMalsero When will the stables be updated? make the other debug unavailable

**Comment by MartensMalsero** [comment]
@hulguu I'm working on a slightly bigger update right now. It will come together with the release. I can't announce an ETA at the moment. But the changes are already done. There are currently 85% ready of the larger update and the internal beta test is already running.

**Comment by hulguu** [comment]
@MartensMalsero  okey bro thanks. Good luck

**Comment by Local9** [comment]
No progress
